### PR TITLE
Change branch context to use same sort as repo context

### PR DESCRIPTION
**Pull request by tomsolem**
Change to use the same sort on branch context as repo context. 

The `--sort=-committerdate` sorts the tags in the wrong order if there are tags on the branch prior to apply this github action on the repo. 

Changing this to use `--sort=-v:refname` will sort the tags in the same order as the repo context. 

https://git-scm.com/docs/git-tag#Documentation/git-tag.txt---sortltkeygt

### CODE REVIEW

**Review by anothrNick — APPROVED** [review]
Just needs a rebase or merge from master

**Comment by tomsolem** [comment]
I merged with master. I added my changes into the new merged file.

**Comment by anothrNick** [comment]
Thank you @tomsolem , I apologize for the late review/merge.

**Comment by fermoya** [comment]
Hi @tomsolem and @anothrNick , this brings back issue https://github.com/anothrNick/github-tag-action/issues/76. If you order by refname, it prioritizes tags which are prefixed by `v`. 

So if someone started using tags like:
```
v0.1.0
v0.2.0
```
and at some point, they changed their minds and dropped the prefix:
```
v0.1.0
v0.2.0
1.0.0
```
Then this PR breaks the GitFlow, as the tags will be sorted prioritizing those prefixed by `v` and therefore the bumped tag would be `v0.2.0` which turns into `1.0.0` with a major bump (as they don't use a prefix any more, `WITH_V` is set to false). This makes the flow fail.

Why did you change it @tomsolem ? If you're interested in the branch context, you can use `TAG_CONTEXT: branch`. This will use `--sort=-v:refname` rather than `commiterdate`. 

In my opinion, tags should be sorted by date.

**Comment by jesigloot** [comment]
Can confirm that this break things in a repo that does exactly the scenario above. Reverting to using 1.32.0.

**Pull request merged**
