### PR TITLE
Fix: Get the default branch from env vars also allow to overwrite as parameter

### PR DESCRIPTION
**Pull request by sbe-arg**
Hotfix

### CODE REVIEW

**Review by sammcj — APPROVED** [review]

**Comment by sbe-arg** [comment]
I'm back lets merge this

**Comment by martinjlowm** [comment]
This broke our CI with:
```
The DEFAULT_BRANCH should be autodetected when tag-action runs on on PRs else must be defined, See: https://github.com/anothrNick/github-tag-action/pull/230, since is not defined we find it natively
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
default_branch=
```
Apparently, the `GITHUB_BASE_REF` fallback is empty as well.

**Comment by JP-Dhabolt** [comment]
@sbe-arg @sammcj 
This change was not backwards compatible and broke our CI as well.
```
The DEFAULT_BRANCH should be autodetected when tag-action runs on on PRs else must be defined, See: https://github.com/anothrNick/github-tag-action/pull/230, since is not defined we find it natively
fatal: ref refs/remotes/origin/HEAD is not a symbolic ref
default_branch=
Error: DEFAULT_BRANCH must not be null, something has gone wrong.
```

**Comment by Drew-Kimberly** [comment]
+1 to the above. This change broke our CI as well w/ the same error

**Comment by PrakharSrivastav** [comment]
+1 . Broke the existing CI

**Comment by afranzoy** [comment]
+1 broke our CI pipenline with the error: "DEFAULT_BRANCH must not be null, something has gone wrong."

**Comment by sonyavera** [comment]
+1

**Comment by artem-tomyuk** [comment]
+1

**Comment by sammcj** [comment]
This project badly needs tests, especially if folks are going to run the action from main.

@sbe-arg please revert

**Comment by sammcj** [comment]
If anyone here is/was affected by this breaking change, has developing (or test automation) skills and is interested to helping to maintain this project - please let let me or @sbe-arg know.

This project isn't ours, we've just been added as contributors because it went unmaintained for some time. The project doesn't have reasonable test coverage (see #184), which is in part why we suggest people don't run it from main/master unless you're happy to be testing cutting edge changes.

We're only two folks, in the same time zone so it's currently very much a best effort as we both work full time and have social lives etc...

**Pull request merged**
