### PR TITLE
fix: safe sub directory

### LINKED ISSUE #148: unsafe repository error still present on 1.39.0
Hello !
I've run into the unsafe repository error so we bumped to 1.39.0.
After some tests it seems like the issue is still happening :(

```
Run anothrNick/github-tag-action@1.39.0
  env:
    NPM_CONFIG_USERCONFIG: /home/runner/work/_temp/.npmrc
    NODE_AUTH_TOKEN: XXXXX-XXXXX-XXXXX-XXXXX
    package_version: 9.[2]([censored]?check_suite_focus=true#step:11:2).6
    GITHUB_TOKEN: ***
    WITH_V: true
    SOURCE: main
/usr/bin/docker run --name bcf0907966ec2e0c14a4a86c0b5f90aff7[3]([censored])80_ce5a2a --label 2bcf09 --workdir /github/workspace --rm -e NPM_CONFIG_USERCONFIG -e NODE_AUTH_TOKEN -e package_version -e GITHUB_TOKEN -e WITH_V -e SOURCE -e HOME -e GITHUB_JOB -e GITHUB_REF -e GITHUB_SHA -e GITHUB_REPOSITORY -e GITHUB_REPOSITORY_OWNER -e GITHUB_RUN_ID -e GITHUB_RUN_NUMBER -e GITHUB_RETENTION_DAYS -e GITHUB_RUN_ATTEMPT -e GITHUB_ACTOR -e GITHUB_WORKFLOW -e GITHUB_HEAD_REF -e GITHUB_BASE_REF -e GITHUB_EVENT_NAME -e GITHUB_SERVER_URL -e GITHUB_API_URL -e GITHUB_GRAPHQL_URL -e GITHUB_REF_NAME -e GITHUB_REF_PROTECTED -e GITHUB_REF_TYPE -e GITHUB_WORKSPACE -e GITHUB_ACTION -e GITHUB_EVENT_PATH -e GITHUB_ACTION_REPOSITORY -e GITHUB_ACTION_REF -e GITHUB_PATH -e GITHUB_ENV -e GITHUB_STEP_SUMMARY -e RUNNER_OS -e RUNNER_ARCH -e RUNNER_NAME -e RUNNER_TOOL_CACHE -e RUNNER_TEMP -e RUNNER_WORKSPACE -e ACTIONS_RUNTIME_URL -e ACTIONS_RUNTIME_TOKEN -e ACTIONS_CACHE_URL -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/skillup/skillup":"/github/workspace" 2bcf09:07966ec2e0c1[4]([censored])a4a86c0b[5]([censored])f90aff[7]([censored])3[8]([censored])0
*** CONFIGURATION ***
	DEFAULT_BUMP: minor
	WITH_V: true
	RELEASE_BRANCHES: master,main
	CUSTOM_TAG: 
	SOURCE: main
	DRY_RUN: false
	INITIAL_VERSION: 0.0.0
	TAG_CONTEXT: repo
	PRERELEASE_SUFFIX: beta
	VERBOSE: true
fatal: unsafe repository ('/github/workspace/main' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/main
fatal: unsafe repository ('/github/workspace/main' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/main
Is master a match for 
Is main a match for 
pre_release = true
fatal: unsafe repository ('/github/workspace/main' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/main
fatal: unsafe repository ('/github/workspace/main' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/main
fatal: unsafe repository ('/github/workspace/main' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/main
fatal: unsafe repository ('/github/workspace/main' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/main
fatal: unsafe repository ('/github/workspace/main' is owned by someone else)
To add an exception for this directory, call:

	git config --global --add safe.directory /github/workspace/main
```

### PR DESCRIPTION
**Pull request by jordanamr**
Fixes #148

### CODE REVIEW

**Comment by jordanamr** [comment]
If anyone is stuck on that issue and rely on that action, we forked and fixed that at our company while the author is away :)
Feel free to use `skillupco/github-tag-action@1.39.0-skco`

**Comment by sammcj** [comment]
@jordanamr are the $GITHUB_WORKSPACE and $SOURCE variables definitely available _inside_ the containers?

**Comment by jordanamr** [comment]
> @jordanamr are the $GITHUB_WORKSPACE and $SOURCE variables definitely available _inside_ the containers?

Yes. They are used and/or defined in the entrypoint.sh.

**Comment by jordanamr** [comment]
> @jordanamr are the $GITHUB_WORKSPACE and $SOURCE variables definitely available _inside_ the containers?

Unsure. They are used and/or defined in the entrypoint.sh.

**Comment by sammcj** [comment]
OK thanks @jordanamr, I _think_ it should be OK, I've been added to the list of maintainers for this repo so am happy to approve and merge it, my only concern is that there aren't any tests for this project (yet) so I'm flying blind a bit.

If I was to merge and let it release - would you be happy to switch back to this main repo and confirm that your issue is resolved for me?

**Review by sammcj — APPROVED** [review]

**Pull request merged**
