### PR TITLE
Fix Auto Releases

### PR DESCRIPTION
**Pull request by gabriel-stackhouse**
# Summary of changes

Poking around in this repository, I saw your comment in your main workflow file that auto-release creation was broken. Seeing as I have auto-releases working splendidly for my organization, I figured I'd pass along my config if you were interested in using it.

Feel free to change/tweak/adjust whatever you like here, or to reject it entirely.  Completely up to you.

## Breaking Changes

NO

## How changes have been tested

Ran the workflow on my own forked repo [with success](https://github.com/gabriel-stackhouse/github-tag-action/releases/tag/0.1.0):

image

## List any unknowns

N/A

### CODE REVIEW

**Comment by sbe-arg** [comment]
To clarify this we closed as we only release this repo using self action not third party actions.

**Comment by anothrNick** [comment]
Re-opened as https://github.com/softprops/action-gh-release looks like a better alternative to the archived action we currently use for releases.

**Comment by sbe-arg** [comment]
If we merge as is it won't trigger a release because we are not updating the entrypoint or dockerfile etc.

I would suggest adding a comment somewhere to force a release at merge.

No further comments from me.

**Comment by gabriel-stackhouse** [comment]
Rebased on master, removed the placeholder comments, and threw in a comment to `entrypoint.sh` to trigger the workflow run.  Tested working on my own repo.

Let me know if you have any more concerns or questions.

**Review by sbe-arg — APPROVED** [review]

**Comment by sbe-arg** [comment]
Approved. Not sure why I cannot merge

**Review by sbe-arg — APPROVED** [review]

**Comment by sbe-arg** [comment]
Assuming @anothrNick you changed my permissions?

**Comment by anothrNick** [comment]
I haven't changed your permissions. Maybe because I reopened? Not sure

**Comment by sbe-arg** [comment]
Can @gabriel-stackhouse and or @anothrNick merge this.

**Comment by gabriel-stackhouse** [comment]
@sbe-arg I don't have write permissions to the repo, so I'm also unable to merge.

@anothrNick?

**Pull request merged**
