### PR TITLE
feat: pre-build dockerfile

### PR DESCRIPTION
**Pull request by sammcj**
# Summary of changes

Fix for https://github.com/anothrNick/github-tag-action/issues/163

- Build, label, tag and publish Docker image to Githubs image repository.
- Simplify Action's Dockerfile to pull the built image.

Do any of the followings changes break current behaviour or configuration?

- No

## How changes have been tested

- I've forked the repo and done the build and publish.
- Tested I'm able to pull the built image locally.

## List any unknowns

- I haven't tested the changes in _this_ repo.
	- I don't know what package permissions @anothrNick has setup on this repo, if it's default I believe public repos have public packages.

Once merged, the Action should be tested to ensure it's operating the same.

### CODE REVIEW

**Comment by sammcj** [comment]
Note @sbe-arg the build will never work for this PR as it's running the build workflow from main - rather than the branch.

_(One of the many limitations of Github Actions is that you can't trigger a workflow run on a PR that creates the workflow - it has to be merged into main first 😞)_

**Comment by sbe-arg** [comment]
Can we test this in a fork and show proof then we merge master against master.
Is not urgent? Ill try to test during the weekend.

**Comment by sbe-arg** [comment]
But at first sight I like it.

**Comment by sammcj** [comment]
@sbe-arg note I believe the test-action is only failing to pull the image because - it doesn't exist yet 😄

**Review by sbe-arg — APPROVED** [review]
Merge and ping me if anything goes wrong but looks good

**Comment by sammcj** [comment]
Thanks, will do and I'll just revert it right away, no point in stuffing around etc... 😄

**Comment by sammcj** [comment]
aww 😢 looking into why the post-merge build failed

**Comment by sammcj** [comment]
follow up PR up https://github.com/anothrNick/github-tag-action/pull/219
if that doesn't work, I'll revert.

**Pull request merged**
