### PR TITLE
Add tag message override

### PR DESCRIPTION
**Pull request by omerap12**
# Summary of changes
Add an options for overriding the commit message with  custom tag message.

## Breaking Changes

Do any of the included changes break current behaviour or configuration?

NO

## How changes have been tested
Running locally.
-

## List any unknowns

-

### CODE REVIEW

**Comment by anothrNick** [comment]
Sure thing. I'll take a look in a few hours. Thank you for reminding me

**Comment by omerap12** [comment]
> Sure thing. I'll take a look in a few hours. Thank you for reminding me

Cool. Thanks!

**Comment by omerap12** [comment]
Friendly ping :)

**Review by anothrNick — APPROVED** [review]

**Comment by anothrNick** [comment]
Woops... Sorry! Approved

**Comment by omerap12** [comment]
> Woops... Sorry! Approved

Great Thanks! should I add this to the README file?

**Pull request merged**
