### PR TITLE
Creating FORCE option

### PR DESCRIPTION
**Pull request by jcvegan**
# Summary of changes
Adding a FORCE option to skip the condition if the release commit is the same commit from the tag.
This will allow users to create  hotfix from a last release branch.

Added the FORCE option and add also the condition to skip the validation on commit.

## Breaking Changes

Do any of the included changes break current behaviour or configuration?

(YES / **NO**)

## How changes have been tested

-

## List any unknowns

-

### CODE REVIEW

**Comment by jcvegan** [comment]
> I can't test this for a few more weeks and not sure I understand value adding this force option as the idea is to not do anything if the there are no changes. It defeats the purpose of bumping versions only when changes are found.
> 
> Maybe explain a bit more of some scenarios where this option is usefull.

@sbe-arg  yes sure.
First thanks for the effort on this solution.

The scenario we are facing is, we have a release tag (where we have found an issue). So we want to create another release branch where we will fix the issue.
So what we have done is the following:
- Create a branch from the tag with bug
- From that new branch we want to create a new release branch, And here is where the validation does not allow us to create a new release branch. Because comparing to the latest release branch, they are the same. So I came out with adding a force, to skip the validation and create that new release branch.

That's the way I thought can resolve our scenario.

Again thanks for this solution :)

**Comment by sbe-arg** [comment]
What if we rename the force to something like.

Update without commit changes.

force_without_changes or alike.

I'm still not sure about how this will impact existing workflows

**Comment by jcvegan** [comment]
> What if we rename the force to something like.
> 
> Update without commit changes.
> 
> force_without_changes or alike.
> 
> I'm still not sure about how this will impact existing workflows

@sbe-arg code updated

**Comment by gyar-denim** [comment]
Hey all, 
We also need the force option. @jcvegan  thanks for implementing this feature.

**Comment by sbe-arg** [comment]
The problem is I can merge it but I cannot test it.

If I merge and there is trouble ill revert unless you keep and eye on this for a few days post merge.

**Review by sbe-arg — APPROVED** [review]

**Comment by jcvegan** [comment]
@sbe-arg the build had failed, but I am not sure what is causing that issue. https://github.com/anothrNick/github-tag-action/actions/runs/8291496983/job/22691303650#step:4:336

Seems to be a permission issue. For sure I can follow up on this change after it is published. I have a couple of repositories where I can test it

**Comment by sbe-arg** [comment]
We might need @anothrNick to add bot permissions bot the repo settings level

**Comment by sbe-arg** [comment]
I think this is related to the checkout v3.
We need to bump to checkout 4.1.2 and add dependabot as well.

**Comment by anothrNick** [comment]
> We might need @anothrNick to add bot permissions bot the repo settings level

What do you need here?

**Comment by sbe-arg** [comment]
@anothrNick in theory this should fix the permission error to release this repo https://github.com/anothrNick/github-tag-action/pull/307

**Comment by sbe-arg** [comment]
@jcvegan forgot to edit the dockerfile or the entrypoint to trigger a new release.
want to open a pr to bump to alpine node 20? good excuse

**Comment by jcvegan** [comment]
> @jcvegan forgot to edit the dockerfile or the entrypoint to trigger a new release. want to open a pr to bump to alpine node 20? good excuse, Ill approve so we can merge

Hi @sbe-arg , I modified the entrypoint but not the dockerfile. Do you want me to create the PR for this change? is it only upgrading the node version?

**Comment by sbe-arg** [comment]
Yes just a docker file edit will trigger a new release

**Comment by jcvegan** [comment]
@sbe-arg just created the PR for that, upgrading node to version 20 https://github.com/anothrNick/github-tag-action/pull/308

**Comment by sbe-arg** [comment]
I have no idea why we suddenly have this problem

```
remote: Permission to anothrNick/github-tag-action.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/anothrNick/github-tag-action/': The requested URL returned error: 403
```
@anothrNick any ideas? we do have https://github.com/anothrNick/github-tag-action/blob/master/.github/workflows/main.yml#L19 write access

**Pull request merged**
