### PR TITLE
Upgrade node to version 20

### PR DESCRIPTION
**Pull request by jcvegan**
# Summary of changes

Update the node version from 18 to 20

## Breaking Changes

Do any of the included changes break current behaviour or configuration?

(**YES** / NO)

## How changes have been tested

-

## List any unknowns

-

### CODE REVIEW

**Review by sbe-arg — APPROVED** [review]

**Comment by jcvegan** [comment]
@sbe-arg still same error :/

**Comment by sbe-arg** [comment]
Yup I have no idea whats going on.

**Comment by jcvegan** [comment]
@sbe-arg seems to be a permission issue https://github.com/anothrNick/github-tag-action/actions/runs/8368227427/job/22911985016#step:4:366 for that user.

**Comment by sbe-arg** [comment]
Its not allowing the github actions bot to create a tag basically but not sure why.

**Comment by jcvegan** [comment]
@sbe-arg maybe related to this https://github.com/ad-m/github-push-action/issues/96. Can you check the branch protection rules and/or the config settings?

**Comment by sbe-arg** [comment]
Nope only @anothrNick can check those settings

**Comment by anothrNick** [comment]
@sbe-arg do we need to explicitly set the `token` for checkout v4? https://github.com/actions/checkout?tab=readme-ov-file#usage

Says the default is `${{ github.token }}`

**Comment by sbe-arg** [comment]
I have no idea why this is happening to be honest.

If the actions settings did not change for this repo it should work.

**Pull request merged**
